---
version: 2
env:
  - VAULT111=1.11.12
  - VAULT112=1.12.11
  - VAULT113=1.13.13
  - VAULT114=1.14.10
  - VAULT115=1.15.6
  - VAULT116=1.16.3
  - VAULT117=1.17.6
  - VAULT118=1.18.4
  - SOURCE_DATE_EPOCH=1609459200

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - binary: clickhouse-database-plugin
    main: ./cmd/vault-plugin-database-clickhouse/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -tags=static
    ldflags:
      - -s
      - -w
      - -buildid= # Removes non-deterministic build ID
      - -X main.version={{.Tag}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
dockers:
  ##############
  #  VAULT 1.11
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT111}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT111}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.12
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT112}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT112}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.13
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT113}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT113}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.14
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT114}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT114}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.15
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT115}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT115}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.16
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT116}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT116}}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.17
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT117 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT117 }}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT117 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT117 }}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  ##############
  #  VAULT 1.18
  ##############
  - goos: linux
    goarch: amd64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT118 }}-{{ .Tag }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT118 }}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
  - goos: linux
    goarch: arm64
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT118 }}-{{ .Tag }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VAULT_VERSION={{.Env.VAULT118 }}"
      - "--build-arg=SOURCE_DATE_EPOCH={{.Env.SOURCE_DATE_EPOCH }}"
docker_manifests:
  ##############
  #  VAULT 1.11
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT111 }}-{{ .Tag }}-arm64"
    skip_push: false
  ##############
  #  VAULT 1.12
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT112 }}-{{ .Tag }}-arm64"
    skip_push: false
  ##############
  #  VAULT 1.13
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT113 }}-{{ .Tag }}-arm64"
    skip_push: false
  ##############
  #  VAULT 1.14
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT114 }}-{{ .Tag }}-arm64"
    skip_push: false
  ##############
  #  VAULT 1.15
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT115 }}-{{ .Tag }}-arm64"
    skip_push: false
  ##############
  #  VAULT 1.16
  ##############
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-arm64"
    skip_push: false
  - name_template: "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-latest"
    image_templates:
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-amd64"
      - "contentsquareplatform/vault-plugin-database-clickhouse:{{ .Env.VAULT116 }}-{{ .Tag }}-arm64"
    skip_push: false
snapshot:
  version_template: '{{ .FullCommit }}-SNAPSHOT'
# archives:
#   - id: default
#     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
#     formats:
#       - tar.gz
#     files:
#       - src: LICENCE*
#       - src: README*
#   - id: clickhouse-database-plugin-binary
#     name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
#     formats:
#       - binary

# checksum:
#   algorithm: sha256
#   ids:
#     - clickhouse-database-plugin-binary
# release:
#   ids:
#     - default
