---
builds:
  - binary: clickhouse-database-plugin
    main: ./cmd/vault-plugin-database-clickhouse/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=static
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    gcflags:
      - -trimpath={{.Env.GOPATH}}
snapshot:
  name_template: "{{ .FullCommit }}-SNAPSHOT"