---
name: Lint

on:
  workflow_dispatch:
  push:

jobs:
  golangci-lint:    
    runs-on: ubuntu24-large
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        uses: jdx/mise-action@v3

      - name: golangci-lint
        run: mise run go:lint
