---
name: Lint

on:
  workflow_dispatch:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ContentSquare/actions-checkout@approved-v6

      - name: Set up Go
        uses: ContentSquare/actions-setup-go@approved-v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: contentsquare/golangci-golangci-lint-action@approved-v8
        with:
          version: v2.1.5
