---
name: Tests

on:
  workflow_dispatch:
  push:

jobs:
  tests:    
    runs-on: ubuntu24-large
    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        uses: jdx/mise-action@v3

      - name: Test
        run: mise run go:test
