---
name: Release

on:
  push:
    tags:
      - "v*"
    tags_ignore:
      - "*-test"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install cross-compile package
        run: |
          sudo apt update
          sudo apt install -y gcc gcc-aarch64-linux-gnu musl build-essential

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password  }}

      - name: Run GoReleaser - Docker images
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "2.9.0"
          args: release --debug
        env:
          GOPATH: ${{ env.GOPATH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
